# Copyright (c) 2023 Devexperts LLC.
# SPDX-License-Identifier: MPL-2.0

name: release

on:
  workflow_dispatch:
    inputs:
      publish:
        description: 'Publish The Release'
        default: true
        required: true
        type: boolean
      use_latest_tag:
        description: 'Try To Use The Latest Git Tag'
        default: false
        required: true
        type: boolean

jobs:
  get_version:
    name: Get Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set_version.outputs.version }}
      tag_name: ${{ steps.set_version.outputs.tag_name }}
    steps:
      - uses: actions/checkout@master
        with:
          name: https://github.com/dxFeed/dxfeed-graal-cxx-api
      - id: get_latest_tag
        run: |
          echo "tag=$(git describe --abbrev=0 --tags)"
          echo "tag=$(git describe --abbrev=0 --tags)" >> $GITHUB_OUTPUT

      - id: set_version
        run: |
          if [[ "${{ !inputs.use_latest_tag && startsWith(github.ref, 'refs/tags/') }}" == "true" ]]
          then
            echo "version=${{github.ref_name}}"
            echo "version=${{github.ref_name}}" >> $GITHUB_OUTPUT
            echo "tag_name=${{github.ref}}"
            echo "tag_name=${{github.ref}}" >> $GITHUB_OUTPUT
          else
            echo "version=${{ steps.get_latest_tag.outputs.tag }}"
            echo "version=${{ steps.get_latest_tag.outputs.tag }}" >> $GITHUB_OUTPUT
            echo "tag_name=${{ format('refs/tags/{0}', steps.get_latest_tag.outputs.tag) }}"
            echo "tag_name=${{ format('refs/tags/{0}', steps.get_latest_tag.outputs.tag) }}" >> $GITHUB_OUTPUT            
          fi