# Copyright (c) 2023 Devexperts LLC.
# SPDX-License-Identifier: MPL-2.0

name: release

on:
  workflow_dispatch:
    inputs:
      publish:
        description: 'Publish The Release'
        default: true
        required: true
        type: boolean

jobs:
  get_version:
    name: Get Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set_version.outputs.version }}
      tag_name: ${{ steps.set_version.outputs.tag_name }}
    steps:
      - uses: actions/checkout@master
        with:
          repository: dxFeed/dxfeed-graal-cxx-api
          fetch-tags: true
          fetch-depth: 0
          path: dxfeed-graal-cxx-api
      - id: get_latest_tag
        run: |
          cd $GITHUB_WORKSPACE/dxfeed-graal-cxx-api
          echo "tag=$(git describe --abbrev=0 --tags)"
          echo "tag=$(git describe --abbrev=0 --tags)" >> $GITHUB_OUTPUT

      - id: set_version
        run: |
          echo "version=${{ steps.get_latest_tag.outputs.tag }}"
          echo "version=${{ steps.get_latest_tag.outputs.tag }}" >> $GITHUB_OUTPUT
          echo "tag_name=${{ format('refs/tags/{0}', steps.get_latest_tag.outputs.tag) }}"
          echo "tag_name=${{ format('refs/tags/{0}', steps.get_latest_tag.outputs.tag) }}" >> $GITHUB_OUTPUT

  build_package_and_upload:
    name: Build, Package & Upload
    needs: [ get_version ]
    strategy:
      matrix:
        os: [ windows-latest, macos-13, ubuntu-22.04 ]
        # buildType: [ Release, Debug, RelWithDebInfo, MinSizeRel ]
        # buildType: [ Release, Debug ]
    runs-on: ${{ matrix.os }}
    env:
      XCODE_VERSION: '15.0'
      GCC_VERSION: '12'

    steps:
      - uses: actions/checkout@v3

      - name: Prepare (Win)
        if: ${{ contains(matrix.os, 'windows') }}
        shell: pwsh
        run: |
          scripts/prepare-win.ps1 "${{needs.get_version.outputs.version}}"
